ssh:
  port: 2222
  user: root
  pass: 123456
  commands:
    "whoami": "root\n"
    "uname -a": "Linux fake-honeypot 5.15.0-75-generic #82-Ubuntu SMP Mon Jun 19 14:18:11 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux\n"
ftp:
  port: 2121
  user: root
  pass: 123456
redis:
  port: 6379
  user: root
  pass: 123456
telnet:
  port: 2323
  user: root
  pass: 123456
postgres:
  port: 5432
  user: postgres
  pass: 123456
mysql:
  port: 3306
  user: root
  pass: 123456